services:
  - type: web
    name: download-videos
    runtime: docker
    plan: free
    repo: https://github.com/seu-usuario/seu-repositorio
    region: oregon
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
